universe = vanilla
log = logs/$(set)_$(Cluster)_$(line).log
error = errors/$(set)_$(Cluster)_$(line).err

executable = align_pt1.sh
arguments = $(line) 
output = outputs/$(line)_align.out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = /home/tribeiro/ril_mapping/bwa.tar.gz, /home/tribeiro/ril_mapping/samtools_1.12.tar.gz, /home/tribeiro/ril_mapping/DmelRef.fasta.tar.gz, /home/tribeiro/ril_mapping/Seq/$(line)_R1.fastq.gz, /home/tribeiro/ril_mapping/Seq/$(line)_R2.fastq.gz

requirements =  (OpSysMajorVer == 7)

request_cpus = 1
request_memory = 9600
request_disk = 100000000

Queue line from Seq_list_single.txt
